/* Priyam Sheth · portfolio v3
   Enhancement only. The page reads complete without this file.
   Hero chat simulation, tabs, comparison slider, two demos, counters, bars, copy. */
(() => {
  'use strict';
  document.body.classList.add('js');
  const REDUCED = matchMedia('(prefers-reduced-motion: reduce)').matches;
  const $ = (s, r = document) => r.querySelector(s);
  const $$ = (s, r = document) => Array.from(r.querySelectorAll(s));
  const clamp = (v, a, b) => Math.min(b, Math.max(a, v));
  const wait = ms => new Promise(r => setTimeout(r, REDUCED ? 0 : ms));
  const fmt = new Intl.NumberFormat('en-IN');

  /* ---------- reveals ---------- */
  const io = new IntersectionObserver(es => es.forEach(en => { if (en.isIntersecting) { en.target.classList.add('in'); io.unobserve(en.target); } }), { threshold: 0.1, rootMargin: '0px 0px -6% 0px' });
  $$('.r').forEach(el => { if (REDUCED || el.getBoundingClientRect().top < innerHeight * 0.92) el.classList.add('in'); else io.observe(el); });

  /* ---------- hero: the Palak OS simulation ---------- */
  const chat = $('[data-chat]');
  if (chat) {
    const log = $('.chat', chat), chips = $$('.chip', chat);
    const say = $('[data-say]'), sayTxt = $('[data-say-txt]'), sayOk = $('[data-say-ok]'), bars = $('[data-bars]');
    const H = '<span class="hid" aria-label="amount hidden"></span>';
    const SCRIPTS = {
      sales: {
        you: 'Kal ka sales kitna tha?',
        ok: '✓ Answered from Zoho',
        bot: [`Kal ke <b>sales orders: 4</b>\nTotal amount: ₹ ${H}\nSabse bada order: ${H} Optical, Surat\n\n2 orders abhi approval ke liye pending hain. Approve karun?`]
      },
      bill: {
        you: '📎 vendor-bill-0912.pdf\nYeh bill Zoho mein daal do',
        ok: '✓ Draft bill in Zoho Books',
        bot: [`Bill mil gaya.\nVendor: ${H} Frames Pvt Ltd\n3 line items · GST 12%\nTotal: ₹ ${H}`, `Zoho Books mein <b>Bill #${'<span class="hid"></span>'}</b> draft mein bana diya. Approve karoge to post ho jayega.`]
      },
      report: {
        you: 'Aaj ki report bhejo',
        ok: '✓ Report sent · 7:30 PM format',
        bot: [`📊 <b>Daily Business Report</b>\n📅 Thursday, 09 July 2026\n\n🛒 <b>Sales Orders</b>\nTotal Orders: 4\nTotal Amount: ₹ ${H}\n\n🧾 <b>Invoices</b>\nTotal Invoices: 11\nTotal Amount: ₹ ${H}\nOutstanding: ₹ ${H}\nCollected: ₹ ${H}\n\n💰 <b>Payments Received</b>\nTotal Payments: 0\n\nPalak Enterprise · Auto-generated by PE Assistant`]
      }
    };
    const stamp = () => { const d = new Date(); return d.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }); };
    let running = false;
    const add = (cls, html) => { const m = document.createElement('div'); m.className = 'msg ' + cls; m.innerHTML = html + `<span class="t">${stamp()}</span>`; log.appendChild(m); log.scrollTop = log.scrollHeight; return m; };
    const typing = () => { const t = document.createElement('div'); t.className = 'typing'; t.innerHTML = '<i style="--i:0"></i><i style="--i:1"></i><i style="--i:2"></i>'; log.appendChild(t); log.scrollTop = log.scrollHeight; return t; };
    const run = async key => {
      if (running) return; running = true;
      const s = SCRIPTS[key];
      chips.forEach(c => { c.disabled = true; c.setAttribute('aria-pressed', c.dataset.script === key ? 'true' : 'false'); });
      log.innerHTML = '';
      sayTxt.textContent = '“' + s.you.replace(/\n/g, ' · ') + '”'; sayOk.textContent = 'LISTENING'; bars.hidden = false; say.classList.add('live');
      await wait(350);
      add('you', s.you.replace(/\n/g, '<br>'));
      for (const b of s.bot) {
        const t = typing(); await wait(900 + Math.min(1400, b.length * 6)); t.remove();
        add('bot', b);
      }
      bars.hidden = true; sayOk.textContent = s.ok;
      chips.forEach(c => c.disabled = false); running = false;
    };
    chips.forEach(c => c.addEventListener('click', () => run(c.dataset.script)));
    const first = () => run('sales');
    if (REDUCED) first(); else setTimeout(first, 900);
  }

  /* ---------- see it work: tabs ---------- */
  const tabs = $$('[role="tab"]');
  if (tabs.length) {
    const stage = $('[data-stage]');
    const show = id => {
      tabs.forEach(t => t.setAttribute('aria-selected', String(t.getAttribute('aria-controls') === id)));
      $$('.panel').forEach(p => p.classList.toggle('active', p.id === id));
      const p = document.getElementById(id);
      if (stage && p) { stage.classList.remove('dusk', 'gold', 'rose', 'night'); stage.classList.add(p.dataset.paint || 'dusk'); stage.classList.toggle('on-night', p.dataset.paint === 'night'); }
      if (id === 'p-erp') playAlloc?.(); if (id === 'p-uics') playUics?.(); if (id === 'p-onyx') nudge?.();
    };
    tabs.forEach(t => t.addEventListener('click', () => { show(t.getAttribute('aria-controls')); history.replaceState(null, '', '#see'); }));
    tabs.forEach((t, i) => t.addEventListener('keydown', e => {
      if (e.key !== 'ArrowRight' && e.key !== 'ArrowLeft') return;
      const n = tabs[(i + (e.key === 'ArrowRight' ? 1 : tabs.length - 1)) % tabs.length]; n.focus(); n.click();
    }));
    // deep links from the footer: #see-palak etc.
    const m = location.hash.match(/^#see-(\w+)$/); if (m && document.getElementById('p-' + m[1])) show('p-' + m[1]);
    $$('[data-open-tab]').forEach(a => a.addEventListener('click', e => { const id = a.dataset.openTab; if (document.getElementById(id)) { e.preventDefault(); show(id); document.getElementById('see').scrollIntoView({ behavior: REDUCED ? 'auto' : 'smooth' }); } }));
  }

  /* ---------- comparison slider ---------- */
  let nudge = null;
  $$('.compare').forEach(c => {
    const input = $('input', c);
    const set = v => c.style.setProperty('--cut', `${clamp(v, 0, 100)}%`);
    input.addEventListener('input', () => set(input.value));
    let drag = false;
    const fromX = x => { const r = c.getBoundingClientRect(); const v = ((x - r.left) / r.width) * 100; input.value = v; set(v); };
    c.addEventListener('pointerdown', e => { drag = true; c.setPointerCapture(e.pointerId); fromX(e.clientX); });
    c.addEventListener('pointermove', e => { if (drag) fromX(e.clientX); });
    c.addEventListener('pointerup', () => drag = false); c.addEventListener('pointercancel', () => drag = false);
    set(input.value);
    let done = false;
    nudge = () => { if (done || REDUCED) return; done = true; const t0 = performance.now();
      const go = now => { const p = clamp((now - t0) / 1400, 0, 1), e = 1 - Math.pow(1 - p, 3); const v = 55 - 22 * Math.sin(e * Math.PI); input.value = v; set(v); if (p < 1) requestAnimationFrame(go); };
      setTimeout(() => requestAnimationFrame(go), 400); };
    const cio = new IntersectionObserver(es => es.forEach(en => { if (en.isIntersecting) { nudge(); cio.disconnect(); } }), { threshold: 0.5 }); cio.observe(c);
  });

  /* ---------- ERP allocation demo ---------- */
  let playAlloc = null;
  const alloc = $('[data-alloc]');
  if (alloc) {
    const rows = $$('tbody tr', alloc), bar = $('[data-alloc-status]'); let timers = [];
    const finish = r => { r.dataset.state = r.dataset.final; $('.res', r).textContent = r.dataset.label; $('.pass', r).textContent = r.dataset.final === 'exact' ? '1' : r.dataset.final === 'sub' ? '2' : '—'; };
    const reset = () => { timers.forEach(clearTimeout); timers = []; rows.forEach(r => { r.dataset.state = ''; $('.res', r).textContent = 'waiting'; $('.pass', r).textContent = '·'; }); if (bar) bar.textContent = 'Reading the order file'; };
    playAlloc = () => {
      reset();
      if (REDUCED) { rows.forEach(finish); if (bar) bar.textContent = 'Allocated · 3 exact, 2 substituted, 1 short'; return; }
      let t = 500;
      timers.push(setTimeout(() => { if (bar) bar.textContent = 'Pass 1 · exact matches'; }, t)); t += 200;
      rows.forEach(r => { if (r.dataset.final === 'exact') { timers.push(setTimeout(() => finish(r), t)); t += 260; } });
      timers.push(setTimeout(() => { if (bar) bar.textContent = 'Pass 2 · substitutes within ±0.25 D'; }, t)); t += 400;
      rows.forEach(r => { if (r.dataset.final !== 'exact') { timers.push(setTimeout(() => finish(r), t)); t += 300; } });
      timers.push(setTimeout(() => { if (bar) bar.textContent = 'Allocated · 3 exact, 2 substituted, 1 short'; }, t));
    };
    $('[data-alloc-replay]')?.addEventListener('click', playAlloc);
    const aio = new IntersectionObserver(es => es.forEach(en => { if (en.isIntersecting) { playAlloc(); aio.disconnect(); } }), { threshold: 0.4 }); aio.observe(alloc);
    reset();
  }

  /* ---------- UICS buckets demo ---------- */
  let playUics = null;
  const uics = $('[data-uics]');
  if (uics) {
    const total = { expected: 412, excess: 9, unknown: 3 }, counts = { expected: 0, excess: 0, unknown: 0 };
    const els = Object.fromEntries(Object.keys(total).map(k => [k, $(`[data-b="${k}"]`, uics)]));
    const code = $('[data-scan-code]', uics), n = $('[data-scan-n]', uics);
    const seq = []; for (let i = 0; i < 40; i++) seq.push(i === 12 || i === 27 || i === 33 ? 'excess' : i === 19 ? 'unknown' : 'expected');
    let timers = [];
    const paint = () => Object.keys(counts).forEach(k => { $('.k', els[k]).textContent = fmt.format(counts[k]); $('.fill', els[k]).style.setProperty('--f', (counts[k] / total[k]).toFixed(3)); });
    const finishAll = () => { Object.assign(counts, total); paint(); if (n) n.textContent = fmt.format(424); if (code) code.textContent = 'done'; };
    playUics = () => {
      timers.forEach(clearTimeout); timers = []; Object.keys(counts).forEach(k => counts[k] = 0); paint();
      if (REDUCED) { finishAll(); return; }
      let scanned = 0;
      seq.forEach((k, i) => timers.push(setTimeout(() => {
        const burst = k === 'expected' ? Math.round(total.expected / 36) : 1;
        counts[k] = Math.min(total[k], counts[k] + burst); scanned += burst;
        if (code) code.textContent = 'WE' + String(18000 + ((i * 37) % 900)).padStart(5, '0') + '-C' + (1 + (i % 3));
        if (n) n.textContent = fmt.format(scanned);
        paint();
        if (i === seq.length - 1) timers.push(setTimeout(finishAll, 300));
      }, 150 + i * 95)));
    };
    $('[data-uics-replay]', uics)?.addEventListener('click', playUics);
    const uio = new IntersectionObserver(es => es.forEach(en => { if (en.isIntersecting) { playUics(); uio.disconnect(); } }), { threshold: 0.4 }); uio.observe(uics);
    paint();
  }

  /* ---------- VS bars + counters ---------- */
  const vs = $('.vs'); if (vs) { const vio = new IntersectionObserver(es => es.forEach(en => { if (en.isIntersecting) { vs.classList.add('in'); vio.disconnect(); } }), { threshold: 0.35 }); vio.observe(vs); }
  const run = el => {
    const target = parseFloat(el.dataset.n), suffix = el.dataset.suffix || '', prefix = el.dataset.prefix || '';
    if (REDUCED) { el.textContent = prefix + fmt.format(target) + suffix; return; }
    const t0 = performance.now(), D = 1200;
    const step = now => { const p = clamp((now - t0) / D, 0, 1), e = 1 - Math.pow(1 - p, 4); el.textContent = prefix + fmt.format(Math.round(target * e)) + suffix; if (p < 1) requestAnimationFrame(step); };
    requestAnimationFrame(step);
  };
  const tio = new IntersectionObserver(es => es.forEach(en => { if (en.isIntersecting) { run(en.target); tio.unobserve(en.target); } }), { threshold: 0.6 });
  $$('[data-n]').forEach(el => tio.observe(el));

  /* ---------- screenshot strips: arrows + keyboard ---------- */
  $$('.strip-wrap').forEach(w => {
    const g = $('[data-gallery]', w), prev = $('[data-prev]', w), next = $('[data-next]', w);
    if (!g) return;
    const step = () => { const f = g.querySelector('figure'); return f ? f.getBoundingClientRect().width + 14 : g.clientWidth * .8; };
    const ends = () => { if (prev) prev.disabled = g.scrollLeft <= 4; if (next) next.disabled = g.scrollLeft >= g.scrollWidth - g.clientWidth - 4; };
    prev?.addEventListener('click', () => g.scrollBy({ left: -step(), behavior: REDUCED ? 'auto' : 'smooth' }));
    next?.addEventListener('click', () => g.scrollBy({ left: step(), behavior: REDUCED ? 'auto' : 'smooth' }));
    g.addEventListener('scroll', ends, { passive: true }); ends();
    g.addEventListener('keydown', e => { if (e.key === 'ArrowRight' || e.key === 'ArrowLeft') { e.preventDefault(); g.scrollBy({ left: e.key === 'ArrowRight' ? step() : -step() }); } });
  });

  /* ---------- copy email ---------- */
  $$('[data-copy]').forEach(b => b.addEventListener('click', async () => {
    try { await navigator.clipboard.writeText(b.dataset.copy); b.dataset.done = '1'; const t = b.textContent; b.textContent = 'Copied'; setTimeout(() => { b.textContent = t; b.dataset.done = ''; }, 1600); }
    catch { location.href = 'mailto:' + b.dataset.copy; }
  }));
})();
